@startuml Issue
object Issue
    Issue : String (255) NotNull **Tags** = "#politics #military #foreign"
    Issue : String (255) NotNull **Issue** = "How to cope with foreign military affairs"
    Issue : String (max) NotNull **Description** = "Lorum Lipsum Larum Lorum ..."
    Issue : DateTime DueDate Null = "//<dd.mm.yyyy>//"
    Issue : String (max) ErrorMessage Null = "//<Filled with error message if error happened>//"
    Issue : Save()
    Issue : Cancel()
@enduml