//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pnyx.SmartContracts.Solidity.Contracts {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Pnyx_SmartContracts_Solidity : global::System.Configuration.ApplicationSettingsBase {
        
        private static Pnyx_SmartContracts_Solidity defaultInstance = ((Pnyx_SmartContracts_Solidity)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Pnyx_SmartContracts_Solidity())));
        
        public static Pnyx_SmartContracts_Solidity Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GITREP\\bc\\pnyx\\Backend\\Pnyx.SmartContracts.Solidity\\bin\\Contracts")]
        public string ContractBinaryRoot {
            get {
                return ((string)(this["ContractBinaryRoot"]));
            }
        }
    }
}
