//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pnyx.SmartContracts.Solidity.Contracts {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Pnyx_SmartContracts_Solidity : global::System.Configuration.ApplicationSettingsBase {
        
        private static Pnyx_SmartContracts_Solidity defaultInstance = ((Pnyx_SmartContracts_Solidity)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Pnyx_SmartContracts_Solidity())));
        
        public static Pnyx_SmartContracts_Solidity Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Entwicklung\\GITREP\\Blockchain\\pnyx\\Backend\\Pnyx.SmartContracts.Solidity\\bin\\Co" +
            "ntracts")]
        public string ContractBinaryRoot {
            get {
                return ((string)(this["ContractBinaryRoot"]));
            }
        }
    }
}
