@startuml
class Issue {
    + Issue()
    + Issue(tags:string, title:string, description:string, dueDate:DateTime?)
    + Tags : string <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + DueDate : DateTime? <<get>> <<set>>
    + ErrorMessage : string <<get>>
    + GetTotalStakeCount() : int
    + GetTags() : IEnumerable<string>
    + {static} GetTags(tags:string) : IEnumerable<string>
    + HasTag(tag:string) : bool
    + GetTopSuggestions(limit:int) : List<Suggestion>
    + GetTopSuggestionsPercentage(percentage:decimal, maxCount:int) : List<Suggestion>
    + IsValid() : bool
}
class "List`1"<T> {
}
Issue --> "Id" Guid
Issue --> "CreateDate" DateTime
Issue --> "Suggestions<Suggestion>" "List`1"
@enduml
