apiVersion: 1

datasources:
  - name: Prometheus
    uid: truerepublic-prometheus
    type: prometheus
    access: proxy
    url: http://truerepublic-node:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
