//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pnyx.SmartContracts.Solidity.Contracts.UnitTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Pnyx_SmartContracts_Solidity_Contracts : global::System.Configuration.ApplicationSettingsBase {
        
        private static Pnyx_SmartContracts_Solidity_Contracts defaultInstance = ((Pnyx_SmartContracts_Solidity_Contracts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Pnyx_SmartContracts_Solidity_Contracts())));
        
        public static Pnyx_SmartContracts_Solidity_Contracts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0x7580e7fb49df1c861f0050fae31c2224c6aba908e116b8da44ee8cd927b990b0")]
        public string DefaultPrivateKey {
            get {
                return ((string)(this["DefaultPrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("444444444500")]
        public long DefaultChainId {
            get {
                return ((long)(this["DefaultChainId"]));
            }
        }
    }
}
