[package]
name = "smart_contracts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.10.8"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
no-entrypoint = []