name: Mobile Wallet CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'mobile-wallet/**'
      - '.github/workflows/react-native-ci.yml'
  pull_request:
    paths:
      - 'mobile-wallet/**'
      - '.github/workflows/react-native-ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile-wallet
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npx jest --passWithNoTests
