//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnectString cannot be empty.
        /// </summary>
        internal static string ErrorDbConnectStringCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorDbConnectStringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string ErrorDescriptionIsRequired {
            get {
                return ResourceManager.GetString("ErrorDescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must be &gt;= 5 characters.
        /// </summary>
        internal static string ErrorDescriptionNotLongEnough {
            get {
                return ResourceManager.GetString("ErrorDescriptionNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date must be at least 5 days in the future.
        /// </summary>
        internal static string ErrorDueDateToShort {
            get {
                return ResourceManager.GetString("ErrorDueDateToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Days needs to be set in the constructor.
        /// </summary>
        internal static string ErrorExpirationDaysNeedsToBeSet {
            get {
                return ResourceManager.GetString("ErrorExpirationDaysNeedsToBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue not found.
        /// </summary>
        internal static string ErrorIssueNotFound {
            get {
                return ResourceManager.GetString("ErrorIssueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funding.
        /// </summary>
        internal static string ErrorNotEnoughFounding {
            get {
                return ResourceManager.GetString("ErrorNotEnoughFounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion is already staked for user.
        /// </summary>
        internal static string ErrorSuggestionAlreadyStakedForUser {
            get {
                return ResourceManager.GetString("ErrorSuggestionAlreadyStakedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags are required.
        /// </summary>
        internal static string ErrorTagsAreRequired {
            get {
                return ResourceManager.GetString("ErrorTagsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags must be &gt;= 5 characters.
        /// </summary>
        internal static string ErrorTagsNotLongEnough {
            get {
                return ResourceManager.GetString("ErrorTagsNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        internal static string ErrorTitleIsRequired {
            get {
                return ResourceManager.GetString("ErrorTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must be &gt;= 5 characters.
        /// </summary>
        internal static string ErrorTitleNotLongEnough {
            get {
                return ResourceManager.GetString("ErrorTitleNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Staked Percent needs to be set in constructor.
        /// </summary>
        internal static string ErrorTopStakePercentNeedsToBeSet {
            get {
                return ResourceManager.GetString("ErrorTopStakePercentNeedsToBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type {0} not found.
        /// </summary>
        internal static string ErrorTransactionTypeNotFound {
            get {
                return ResourceManager.GetString("ErrorTransactionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown transaction type name in excel sheet {0}.
        /// </summary>
        internal static string ErrorUnknownTransactionTypeName {
            get {
                return ResourceManager.GetString("ErrorUnknownTransactionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id {0} not found.
        /// </summary>
        internal static string ErrorUserIdNotFound {
            get {
                return ResourceManager.GetString("ErrorUserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet for user id {0} not found.
        /// </summary>
        internal static string ErrorWalletForUserIdNotFound {
            get {
                return ResourceManager.GetString("ErrorWalletForUserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet for user {0} not found.
        /// </summary>
        internal static string ErrorWalletForUserNotFound {
            get {
                return ResourceManager.GetString("ErrorWalletForUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue cannot be edited anymore.
        /// </summary>
        internal static string IssueCannotBeEditedAnymore {
            get {
                return ResourceManager.GetString("IssueCannotBeEditedAnymore", resourceCulture);
            }
        }
    }
}
